"""added Players static data 

Revision ID: 156b754760b0
Revises: 98ce60dfed37
Create Date: 2025-12-15 18:58:46.078016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '156b754760b0'
down_revision: Union[str, Sequence[str], None] = '98ce60dfed37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('player_name', sa.String(), nullable=False))
    op.add_column('players', sa.Column('rookie_season', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('players_team_id_fkey'), 'players', type_='foreignkey')
    op.drop_column('players', 'draft_year')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'team_id')
    op.drop_column('players', 'first_name')
    op.drop_column('players', 'jersey_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('jersey_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('players', sa.Column('draft_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('players_team_id_fkey'), 'players', 'teams', ['team_id'], ['team_id'])
    op.drop_column('players', 'rookie_season')
    op.drop_column('players', 'player_name')
    # ### end Alembic commands ###
