"""added players_teams association table

Revision ID: 336a53979e9d
Revises: 156b754760b0
Create Date: 2025-12-15 19:40:47.517379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '336a53979e9d'
down_revision: Union[str, Sequence[str], None] = '156b754760b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_teams_association',
    sa.Column('players_teams_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('players_teams_id', 'season')
    )
    op.create_index(op.f('ix_player_teams_association_players_teams_id'), 'player_teams_association', ['players_teams_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_teams_association_players_teams_id'), table_name='player_teams_association')
    op.drop_table('player_teams_association')
    # ### end Alembic commands ###
