"""Added roles to users

Revision ID: 842ef564d9f3
Revises: 15770b9b6284
Create Date: 2026-01-04 13:34:12.701248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '842ef564d9f3'
down_revision: Union[str, Sequence[str], None] = '15770b9b6284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    user_roles_enum = postgresql.ENUM('user', 'admin', name='user_roles')
    user_roles_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('users', sa.Column('role', user_roles_enum, nullable=False, server_default='user'))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'role')
    
    # Drop the ENUM type
    user_roles_enum = postgresql.ENUM('user', 'admin', name='user_roles')
    user_roles_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
