"""added Teams logos to db

Revision ID: 98ce60dfed37
Revises: dcad66756cc3
Create Date: 2025-12-14 12:43:29.311169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ce60dfed37'
down_revision: Union[str, Sequence[str], None] = 'dcad66756cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###
    
    # Insert all NBA teams data
    teams_table = sa.table('teams',
        sa.column('team_id', sa.Integer),
        sa.column('full_name', sa.String),
        sa.column('abbreviation', sa.String),
        sa.column('nickname', sa.String),
        sa.column('city', sa.String),
        sa.column('state', sa.String),
        sa.column('conference', sa.String),
        sa.column('year_founded', sa.Integer),
        sa.column('logo', sa.String)
    )
    
    # NBA teams data with logos
    teams_data = [
        # Eastern Conference
        {'team_id': 1610612737, 'full_name': 'Atlanta Hawks', 'abbreviation': 'ATL', 'nickname': 'Hawks', 'city': 'Atlanta', 'state': 'Georgia', 'conference': 'East', 'year_founded': 1949, 'logo': 'logos/atlanta_hawks-primary-2021.png'},
        {'team_id': 1610612738, 'full_name': 'Boston Celtics', 'abbreviation': 'BOS', 'nickname': 'Celtics', 'city': 'Boston', 'state': 'Massachusetts', 'conference': 'East', 'year_founded': 1946, 'logo': 'logos/boston_celtics_logo_primary_19977628.png'},
        {'team_id': 1610612751, 'full_name': 'Brooklyn Nets', 'abbreviation': 'BKN', 'nickname': 'Nets', 'city': 'Brooklyn', 'state': 'New York', 'conference': 'East', 'year_founded': 1976, 'logo': 'logos/brooklyn_nets_logo_primary_2025_sportslogosnet-1501.png'},
        {'team_id': 1610612766, 'full_name': 'Charlotte Hornets', 'abbreviation': 'CHA', 'nickname': 'Hornets', 'city': 'Charlotte', 'state': 'North Carolina', 'conference': 'East', 'year_founded': 1988, 'logo': 'logos/charlotte__hornets_-primary-2015.png'},
        {'team_id': 1610612741, 'full_name': 'Chicago Bulls', 'abbreviation': 'CHI', 'nickname': 'Bulls', 'city': 'Chicago', 'state': 'Illinois', 'conference': 'East', 'year_founded': 1966, 'logo': 'logos/chicago_bulls_logo_primary_19672598.png'},
        {'team_id': 1610612739, 'full_name': 'Cleveland Cavaliers', 'abbreviation': 'CLE', 'nickname': 'Cavaliers', 'city': 'Cleveland', 'state': 'Ohio', 'conference': 'East', 'year_founded': 1970, 'logo': 'logos/cleveland_cavaliers_logo_primary_2023_sportslogosnet-5369.png'},
        {'team_id': 1610612765, 'full_name': 'Detroit Pistons', 'abbreviation': 'DET', 'nickname': 'Pistons', 'city': 'Detroit', 'state': 'Michigan', 'conference': 'East', 'year_founded': 1948, 'logo': 'logos/detroit_pistons_logo_primary_20185710.png'},
        {'team_id': 1610612754, 'full_name': 'Indiana Pacers', 'abbreviation': 'IND', 'nickname': 'Pacers', 'city': 'Indianapolis', 'state': 'Indiana', 'conference': 'East', 'year_founded': 1976, 'logo': 'logos/indiana-pacers-logo-primary-2026-22496872026.png'},
        {'team_id': 1610612748, 'full_name': 'Miami Heat', 'abbreviation': 'MIA', 'nickname': 'Heat', 'city': 'Miami', 'state': 'Florida', 'conference': 'East', 'year_founded': 1988, 'logo': 'logos/burm5gh2wvjti3xhei5h16k8e.gif'},
        {'team_id': 1610612749, 'full_name': 'Milwaukee Bucks', 'abbreviation': 'MIL', 'nickname': 'Bucks', 'city': 'Milwaukee', 'state': 'Wisconsin', 'conference': 'East', 'year_founded': 1968, 'logo': 'logos/milwaukee_bucks_logo_primary_20165763.png'},
        {'team_id': 1610612752, 'full_name': 'New York Knicks', 'abbreviation': 'NYK', 'nickname': 'Knicks', 'city': 'New York', 'state': 'New York', 'conference': 'East', 'year_founded': 1946, 'logo': 'logos/new_york_knicks_logo_primary_2024_sportslogosnet-7170.png'},
        {'team_id': 1610612753, 'full_name': 'Orlando Magic', 'abbreviation': 'ORL', 'nickname': 'Magic', 'city': 'Orlando', 'state': 'Florida', 'conference': 'East', 'year_founded': 1989, 'logo': 'logos/orlando-magic-logo-primary-2026-21794952026.png'},
        {'team_id': 1610612755, 'full_name': 'Philadelphia 76ers', 'abbreviation': 'PHI', 'nickname': '76ers', 'city': 'Philadelphia', 'state': 'Pennsylvania', 'conference': 'East', 'year_founded': 1949, 'logo': 'logos/philadelphia_76ers-primary-2016.png'},
        {'team_id': 1610612761, 'full_name': 'Toronto Raptors', 'abbreviation': 'TOR', 'nickname': 'Raptors', 'city': 'Toronto', 'state': 'Ontario', 'conference': 'East', 'year_founded': 1995, 'logo': 'logos/toronto_raptors-primary-2021.png'},
        {'team_id': 1610612764, 'full_name': 'Washington Wizards', 'abbreviation': 'WAS', 'nickname': 'Wizards', 'city': 'Washington', 'state': 'District of Columbia', 'conference': 'East', 'year_founded': 1963, 'logo': 'logos/washington_wizards-primary-2016.png'},
        
        # Western Conference
        {'team_id': 1610612742, 'full_name': 'Dallas Mavericks', 'abbreviation': 'DAL', 'nickname': 'Mavericks', 'city': 'Dallas', 'state': 'Texas', 'conference': 'West', 'year_founded': 1980, 'logo': 'logos/dallas_mavericks-primary-2018.png'},
        {'team_id': 1610612743, 'full_name': 'Denver Nuggets', 'abbreviation': 'DEN', 'nickname': 'Nuggets', 'city': 'Denver', 'state': 'Colorado', 'conference': 'West', 'year_founded': 1976, 'logo': 'logos/denver_nuggets-primary-2019.png'},
        {'team_id': 1610612744, 'full_name': 'Golden State Warriors', 'abbreviation': 'GSW', 'nickname': 'Warriors', 'city': 'San Francisco', 'state': 'California', 'conference': 'West', 'year_founded': 1946, 'logo': 'logos/golden_state_warriors-primary-2020.png'},
        {'team_id': 1610612745, 'full_name': 'Houston Rockets', 'abbreviation': 'HOU', 'nickname': 'Rockets', 'city': 'Houston', 'state': 'Texas', 'conference': 'West', 'year_founded': 1967, 'logo': 'logos/houston_rockets-primary-2020.png'},
        {'team_id': 1610612746, 'full_name': 'LA Clippers', 'abbreviation': 'LAC', 'nickname': 'Clippers', 'city': 'Los Angeles', 'state': 'California', 'conference': 'West', 'year_founded': 1970, 'logo': 'logos/los_angeles_clippers_logo_primary_2025_sportslogosnet-5542.png'},
        {'team_id': 1610612747, 'full_name': 'Los Angeles Lakers', 'abbreviation': 'LAL', 'nickname': 'Lakers', 'city': 'Los Angeles', 'state': 'California', 'conference': 'West', 'year_founded': 1947, 'logo': 'logos/los_angeles_lakers_logo_primary_2024_sportslogosnet-7324.png'},
        {'team_id': 1610612763, 'full_name': 'Memphis Grizzlies', 'abbreviation': 'MEM', 'nickname': 'Grizzlies', 'city': 'Memphis', 'state': 'Tennessee', 'conference': 'West', 'year_founded': 1995, 'logo': 'logos/memphis_grizzlies-primary-2019.png'},
        {'team_id': 1610612750, 'full_name': 'Minnesota Timberwolves', 'abbreviation': 'MIN', 'nickname': 'Timberwolves', 'city': 'Minneapolis', 'state': 'Minnesota', 'conference': 'West', 'year_founded': 1989, 'logo': 'logos/minnesota_timberwolves-primary-2018.png'},
        {'team_id': 1610612740, 'full_name': 'New Orleans Pelicans', 'abbreviation': 'NOP', 'nickname': 'Pelicans', 'city': 'New Orleans', 'state': 'Louisiana', 'conference': 'West', 'year_founded': 2002, 'logo': 'logos/new_orleans_pelicans_logo_primary_2024_sportslogosnet-9292.png'},
        {'team_id': 1610612760, 'full_name': 'Oklahoma City Thunder', 'abbreviation': 'OKC', 'nickname': 'Thunder', 'city': 'Oklahoma City', 'state': 'Oklahoma', 'conference': 'West', 'year_founded': 1967, 'logo': 'logos/oklahoma-city-thunder-logo-primary-2009-9699.png'},
        {'team_id': 1610612756, 'full_name': 'Phoenix Suns', 'abbreviation': 'PHX', 'nickname': 'Suns', 'city': 'Phoenix', 'state': 'Arizona', 'conference': 'West', 'year_founded': 1968, 'logo': 'logos/phoenix_suns_logo_primary_20143696.png'},
        {'team_id': 1610612757, 'full_name': 'Portland Trail Blazers', 'abbreviation': 'POR', 'nickname': 'Trail Blazers', 'city': 'Portland', 'state': 'Oregon', 'conference': 'West', 'year_founded': 1970, 'logo': 'logos/portland_trail_blazers-primary-2018.png'},
        {'team_id': 1610612758, 'full_name': 'Sacramento Kings', 'abbreviation': 'SAC', 'nickname': 'Kings', 'city': 'Sacramento', 'state': 'California', 'conference': 'West', 'year_founded': 1945, 'logo': 'logos/sacramento_kings-primary-2017.png'},
        {'team_id': 1610612759, 'full_name': 'San Antonio Spurs', 'abbreviation': 'SAS', 'nickname': 'Spurs', 'city': 'San Antonio', 'state': 'Texas', 'conference': 'West', 'year_founded': 1976, 'logo': 'logos/san_antonio_spurs-primary-2018.png'},
        {'team_id': 1610612762, 'full_name': 'Utah Jazz', 'abbreviation': 'UTA', 'nickname': 'Jazz', 'city': 'Salt Lake City', 'state': 'Utah', 'conference': 'West', 'year_founded': 1974, 'logo': 'logos/utah-jazz-logo-primary-2026-1109.png'}
    ]
    
    # Insert teams data
    op.bulk_insert(teams_table, teams_data)


def downgrade() -> None:
    """Downgrade schema."""
    # Delete all teams data first
    op.execute("DELETE FROM teams")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo')
    # ### end Alembic commands ###
