"""added Teams logos to db

Revision ID: 98ce60dfed37
Revises: dcad66756cc3
Create Date: 2025-12-14 12:43:29.311169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ce60dfed37'
down_revision: Union[str, Sequence[str], None] = 'dcad66756cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'logo')
    # ### end Alembic commands ###
