"""added Teams nickame and state columns

Revision ID: dcad66756cc3
Revises: 2ff59f7c981d
Create Date: 2025-12-13 11:56:53.323853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcad66756cc3'
down_revision: Union[str, Sequence[str], None] = '2ff59f7c981d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('nickname', sa.String(), nullable=False))
    op.add_column('teams', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'state')
    op.drop_column('teams', 'nickname')
    # ### end Alembic commands ###
