"""Added user email verification cols

Revision ID: e88720f1555b
Revises: 842ef564d9f3
Create Date: 2026-01-08 18:26:13.141314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88720f1555b'
down_revision: Union[str, Sequence[str], None] = '842ef564d9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add email_verified column as nullable first
    op.add_column('users', sa.Column('email_verified', sa.Integer(), nullable=True))
    
    # Update existing rows to have default value of 0 (not verified)
    op.execute("UPDATE users SET email_verified = 0 WHERE email_verified IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('users', 'email_verified', nullable=False)
    
    op.add_column('users', sa.Column('email_verification_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verification_at')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
