"""Added regular season stats table

Revision ID: f328272f792f
Revises: f6b9e8bf2183
Create Date: 2025-12-17 10:53:57.063426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f328272f792f'
down_revision: Union[str, Sequence[str], None] = 'f6b9e8bf2183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regular_season_stats',
    sa.Column('stats_id', sa.Integer(), nullable=True),
    sa.Column('players_teams_id', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('total_minutes', sa.Integer(), nullable=True),
    sa.Column('total_field_goals_made', sa.Integer(), nullable=True),
    sa.Column('total_field_goals_attempt', sa.Integer(), nullable=True),
    sa.Column('total_threes_goals_made', sa.Integer(), nullable=True),
    sa.Column('total_threes_goals_attempt', sa.Integer(), nullable=True),
    sa.Column('total_free_throws_made', sa.Integer(), nullable=True),
    sa.Column('total_free_throws_attempt', sa.Integer(), nullable=True),
    sa.Column('total_offensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('total_defensive_rebounds', sa.Integer(), nullable=True),
    sa.Column('total_rebounds', sa.Integer(), nullable=True),
    sa.Column('total_assists', sa.Integer(), nullable=True),
    sa.Column('total_steals', sa.Integer(), nullable=True),
    sa.Column('total_blocks', sa.Integer(), nullable=True),
    sa.Column('total_turnovers', sa.Integer(), nullable=True),
    sa.Column('total_personal_fouls', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['players_teams_id'], ['player_teams_association.players_teams_id'], ),
    sa.PrimaryKeyConstraint('stats_id')
    )
    op.create_index(op.f('ix_regular_season_stats_stats_id'), 'regular_season_stats', ['stats_id'], unique=False)
    op.alter_column('player_teams_association', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('player_teams_association', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('player_teams_association_player_id_team_id_season_key'), 'player_teams_association', type_='unique')
    op.create_index(op.f('ix_player_teams_association_players_teams_id'), 'player_teams_association', ['players_teams_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_teams_association_players_teams_id'), table_name='player_teams_association')
    op.create_unique_constraint(op.f('player_teams_association_player_id_team_id_season_key'), 'player_teams_association', ['player_id', 'team_id', 'season'], postgresql_nulls_not_distinct=False)
    op.alter_column('player_teams_association', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player_teams_association', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_regular_season_stats_stats_id'), table_name='regular_season_stats')
    op.drop_table('regular_season_stats')
    # ### end Alembic commands ###
